export let missingData =[
 {
   "Week": 1,
   "PlayerName": "Christian McCaffrey",
   "PlayerScoreActual": "22.900000000000002",
   "PlayerScoreProjected": "12.439971600000002",
   "PlayerRosterSlotId": 2,
   "PlayerFantasyTeam": 1,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 25,
   "PlayerRosterSlot": "RB"
 },
 {
   "Week": 1,
   "PlayerName": "Amon-Ra St. Brown",
   "PlayerScoreActual": "13.100000000000001",
   "PlayerScoreProjected": "9.9887154526",
   "PlayerRosterSlotId": 4,
   "PlayerFantasyTeam": 1,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 8,
   "PlayerRosterSlot": "WR"
 },
 {
   "Week": 1,
   "PlayerName": "Chris Olave",
   "PlayerScoreActual": "11.200000000000001",
   "PlayerScoreProjected": "9.389751321",
   "PlayerRosterSlotId": 4,
   "PlayerFantasyTeam": 1,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 18,
   "PlayerRosterSlot": "WR"
 },
 {
   "Week": 1,
   "PlayerName": "Justin Fields",
   "PlayerScoreActual": "14.540000000000001",
   "PlayerScoreProjected": "19.484417159",
   "PlayerRosterSlotId": 0,
   "PlayerFantasyTeam": 1,
   "Position": "QB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 3,
   "PlayerRosterSlot": "QB"
 },
 {
   "Week": 1,
   "PlayerName": "J.K. Dobbins",
   "PlayerScoreActual": "9.7",
   "PlayerScoreProjected": "10.978387292999999",
   "PlayerRosterSlotId": 2,
   "PlayerFantasyTeam": 1,
   "Position": "RB",
   "Injured": true,
   "InjuryStatus": "INJURY_RESERVE",
   "ProTeam": 33,
   "PlayerRosterSlot": "RB"
 },
 {
   "Week": 1,
   "PlayerName": "David Montgomery",
   "PlayerScoreActual": "13.4",
   "PlayerScoreProjected": "9.740392642",
   "PlayerRosterSlotId": 23,
   "PlayerFantasyTeam": 1,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 8,
   "PlayerRosterSlot": "FLEX"
 },
 {
   "Week": 1,
   "PlayerName": "Jahan Dotson",
   "PlayerScoreActual": "4.0",
   "PlayerScoreProjected": "7.443276161",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 1,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 28,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Gabe Davis",
   "PlayerScoreActual": "3.2",
   "PlayerScoreProjected": "6.936784944999999",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 1,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "QUESTIONABLE",
   "ProTeam": 2,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Zach Charbonnet",
   "PlayerScoreActual": "1.1",
   "PlayerScoreProjected": "6.4628800436",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 1,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 26,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Rashod Bateman",
   "PlayerScoreActual": "3.5",
   "PlayerScoreProjected": "4.618734343999999",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 1,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 33,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Evan Engram",
   "PlayerScoreActual": "4.9",
   "PlayerScoreProjected": "6.0483015923",
   "PlayerRosterSlotId": 6,
   "PlayerFantasyTeam": 1,
   "Position": "TE",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 30,
   "PlayerRosterSlot": "TE"
 },
 {
   "Week": 1,
   "PlayerName": "Roschon Johnson",
   "PlayerScoreActual": "11.5",
   "PlayerScoreProjected": "1.6482779546",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 1,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 3,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Evan McPherson",
   "PlayerScoreActual": "4.0",
   "PlayerScoreProjected": "8.53841388",
   "PlayerRosterSlotId": 17,
   "PlayerFantasyTeam": 1,
   "Position": "K",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 4,
   "PlayerRosterSlot": "K"
 },
 {
   "Week": 1,
   "PlayerName": "Juwan Johnson",
   "PlayerScoreActual": "3.6",
   "PlayerScoreProjected": "5.185048989",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 1,
   "Position": "TE",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 18,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Commanders D/ST",
   "PlayerScoreActual": "10.0",
   "PlayerScoreProjected": "7.838866715000003",
   "PlayerRosterSlotId": 16,
   "PlayerFantasyTeam": 1,
   "Position": "D/ST",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 28,
   "PlayerRosterSlot": "D/ST"
 },
 {
   "Week": 1,
   "PlayerName": "Luke Musgrave",
   "PlayerScoreActual": "5.0",
   "PlayerScoreProjected": "4.1508301979999995",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 1,
   "Position": "TE",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 9,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Travis Kelce",
   "PlayerScoreActual": "0.0",
   "PlayerScoreProjected": "0.0",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 2,
   "Position": "TE",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 12,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "A.J. Brown",
   "PlayerScoreActual": "7.9",
   "PlayerScoreProjected": "9.709252791",
   "PlayerRosterSlotId": 4,
   "PlayerFantasyTeam": 2,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "QUESTIONABLE",
   "ProTeam": 21,
   "PlayerRosterSlot": "WR"
 },
 {
   "Week": 1,
   "PlayerName": "Jalen Hurts",
   "PlayerScoreActual": "12.5",
   "PlayerScoreProjected": "21.312008779",
   "PlayerRosterSlotId": 0,
   "PlayerFantasyTeam": 2,
   "Position": "QB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 21,
   "PlayerRosterSlot": "QB"
 },
 {
   "Week": 1,
   "PlayerName": "Alexander Mattison",
   "PlayerScoreActual": "10.4",
   "PlayerScoreProjected": "11.978816362999998",
   "PlayerRosterSlotId": 2,
   "PlayerFantasyTeam": 2,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 16,
   "PlayerRosterSlot": "RB"
 },
 {
   "Week": 1,
   "PlayerName": "James Cook",
   "PlayerScoreActual": "6.300000000000001",
   "PlayerScoreProjected": "9.377386467",
   "PlayerRosterSlotId": 2,
   "PlayerFantasyTeam": 2,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 2,
   "PlayerRosterSlot": "RB"
 },
 {
   "Week": 1,
   "PlayerName": "Christian Kirk",
   "PlayerScoreActual": "0.9",
   "PlayerScoreProjected": "7.848807234300001",
   "PlayerRosterSlotId": 4,
   "PlayerFantasyTeam": 2,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "QUESTIONABLE",
   "ProTeam": 30,
   "PlayerRosterSlot": "WR"
 },
 {
   "Week": 1,
   "PlayerName": "Jordan Addison",
   "PlayerScoreActual": "12.100000000000001",
   "PlayerScoreProjected": "6.2383636903",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 2,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 16,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Treylon Burks",
   "PlayerScoreActual": "2.7",
   "PlayerScoreProjected": "6.3840655475000005",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 2,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 10,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Kenneth Gainwell",
   "PlayerScoreActual": "7.4",
   "PlayerScoreProjected": "7.788470201400001",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 2,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 21,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Romeo Doubs",
   "PlayerScoreActual": "14.6",
   "PlayerScoreProjected": "6.149507659",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 2,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 9,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Jameson Williams",
   "PlayerScoreActual": "0.0",
   "PlayerScoreProjected": "0.0",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 2,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 8,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Daniel Jones",
   "PlayerScoreActual": "4.46",
   "PlayerScoreProjected": "17.495903412000004",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 2,
   "Position": "QB",
   "Injured": true,
   "InjuryStatus": "INJURY_RESERVE",
   "ProTeam": 19,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Jason Myers",
   "PlayerScoreActual": "8.0",
   "PlayerScoreProjected": "8.821818377",
   "PlayerRosterSlotId": 17,
   "PlayerFantasyTeam": 2,
   "Position": "K",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 26,
   "PlayerRosterSlot": "K"
 },
 {
   "Week": 1,
   "PlayerName": "Khalil Herbert",
   "PlayerScoreActual": "8.4",
   "PlayerScoreProjected": "9.239403096000002",
   "PlayerRosterSlotId": 23,
   "PlayerFantasyTeam": 2,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 3,
   "PlayerRosterSlot": "FLEX"
 },
 {
   "Week": 1,
   "PlayerName": "Jaguars D/ST",
   "PlayerScoreActual": "11.0",
   "PlayerScoreProjected": "7.364305077",
   "PlayerRosterSlotId": 16,
   "PlayerFantasyTeam": 2,
   "Position": "D/ST",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 30,
   "PlayerRosterSlot": "D/ST"
 },
 {
   "Week": 1,
   "PlayerName": "Tyler Higbee",
   "PlayerScoreActual": "4.9",
   "PlayerScoreProjected": "6.872544240000001",
   "PlayerRosterSlotId": 6,
   "PlayerFantasyTeam": 2,
   "Position": "TE",
   "Injured": false,
   "InjuryStatus": "QUESTIONABLE",
   "ProTeam": 14,
   "PlayerRosterSlot": "TE"
 },
 {
   "Week": 1,
   "PlayerName": "Saquon Barkley",
   "PlayerScoreActual": "6.300000000000001",
   "PlayerScoreProjected": "12.979829501000001",
   "PlayerRosterSlotId": 2,
   "PlayerFantasyTeam": 4,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 19,
   "PlayerRosterSlot": "RB"
 },
 {
   "Week": 1,
   "PlayerName": "Davante Adams",
   "PlayerScoreActual": "6.6000000000000005",
   "PlayerScoreProjected": "12.672255966700002",
   "PlayerRosterSlotId": 4,
   "PlayerFantasyTeam": 4,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 13,
   "PlayerRosterSlot": "WR"
 },
 {
   "Week": 1,
   "PlayerName": "Josh Allen",
   "PlayerScoreActual": "9.04",
   "PlayerScoreProjected": "21.08435756",
   "PlayerRosterSlotId": 0,
   "PlayerFantasyTeam": 4,
   "Position": "QB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 2,
   "PlayerRosterSlot": "QB"
 },
 {
   "Week": 1,
   "PlayerName": "Amari Cooper",
   "PlayerScoreActual": "3.7",
   "PlayerScoreProjected": "8.891053517000001",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 4,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 5,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Terry McLaurin",
   "PlayerScoreActual": "3.1",
   "PlayerScoreProjected": "8.67113769",
   "PlayerRosterSlotId": 4,
   "PlayerFantasyTeam": 4,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 28,
   "PlayerRosterSlot": "WR"
 },
 {
   "Week": 1,
   "PlayerName": "Brian Robinson Jr.",
   "PlayerScoreActual": "12.6",
   "PlayerScoreProjected": "9.971954715",
   "PlayerRosterSlotId": 2,
   "PlayerFantasyTeam": 4,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 28,
   "PlayerRosterSlot": "RB"
 },
 {
   "Week": 1,
   "PlayerName": "Jamaal Williams",
   "PlayerScoreActual": "5.2",
   "PlayerScoreProjected": "11.847537885",
   "PlayerRosterSlotId": 23,
   "PlayerFantasyTeam": 4,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 18,
   "PlayerRosterSlot": "FLEX"
 },
 {
   "Week": 1,
   "PlayerName": "Michael Pittman Jr.",
   "PlayerScoreActual": "15.700000000000001",
   "PlayerScoreProjected": "7.1100078061000005",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 4,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 11,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Jerick McKinnon",
   "PlayerScoreActual": "1.0",
   "PlayerScoreProjected": "7.889307249000002",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 4,
   "Position": "RB",
   "Injured": true,
   "InjuryStatus": "INJURY_RESERVE",
   "ProTeam": 12,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Elijah Moore",
   "PlayerScoreActual": "6.2",
   "PlayerScoreProjected": "5.5124068551",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 4,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 5,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Kadarius Toney",
   "PlayerScoreActual": "0.0",
   "PlayerScoreProjected": "7.1547075630000005",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 4,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "QUESTIONABLE",
   "ProTeam": 12,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "De'Von Achane",
   "PlayerScoreActual": "0.0",
   "PlayerScoreProjected": "0.0",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 4,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 15,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Irv Smith Jr.",
   "PlayerScoreActual": "1.7000000000000002",
   "PlayerScoreProjected": "3.92990914",
   "PlayerRosterSlotId": 6,
   "PlayerFantasyTeam": 4,
   "Position": "TE",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 4,
   "PlayerRosterSlot": "TE"
 },
 {
   "Week": 1,
   "PlayerName": "Bryce Young",
   "PlayerScoreActual": "7.54",
   "PlayerScoreProjected": "14.120961585",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 4,
   "Position": "QB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 29,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Eagles D/ST",
   "PlayerScoreActual": "12.0",
   "PlayerScoreProjected": "7.151098769000001",
   "PlayerRosterSlotId": 16,
   "PlayerFantasyTeam": 4,
   "Position": "D/ST",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 21,
   "PlayerRosterSlot": "D/ST"
 },
 {
   "Week": 1,
   "PlayerName": "Brandon McManus",
   "PlayerScoreActual": "8.0",
   "PlayerScoreProjected": "8.522381949",
   "PlayerRosterSlotId": 17,
   "PlayerFantasyTeam": 4,
   "Position": "K",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 30,
   "PlayerRosterSlot": "K"
 },
 {
   "Week": 1,
   "PlayerName": "Stefon Diggs",
   "PlayerScoreActual": "16.200000000000003",
   "PlayerScoreProjected": "9.895010335",
   "PlayerRosterSlotId": 4,
   "PlayerFantasyTeam": 7,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 2,
   "PlayerRosterSlot": "WR"
 },
 {
   "Week": 1,
   "PlayerName": "Josh Jacobs",
   "PlayerScoreActual": "7.100000000000001",
   "PlayerScoreProjected": "13.416885854",
   "PlayerRosterSlotId": 2,
   "PlayerFantasyTeam": 7,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "QUESTIONABLE",
   "ProTeam": 13,
   "PlayerRosterSlot": "RB"
 },
 {
   "Week": 1,
   "PlayerName": "DeVonta Smith",
   "PlayerScoreActual": "10.7",
   "PlayerScoreProjected": "8.802890626",
   "PlayerRosterSlotId": 4,
   "PlayerFantasyTeam": 7,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 21,
   "PlayerRosterSlot": "WR"
 },
 {
   "Week": 1,
   "PlayerName": "Lamar Jackson",
   "PlayerScoreActual": "6.5600000000000005",
   "PlayerScoreProjected": "22.515392988000002",
   "PlayerRosterSlotId": 0,
   "PlayerFantasyTeam": 7,
   "Position": "QB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 33,
   "PlayerRosterSlot": "QB"
 },
 {
   "Week": 1,
   "PlayerName": "Isiah Pacheco",
   "PlayerScoreActual": "5.4",
   "PlayerScoreProjected": "10.042212417",
   "PlayerRosterSlotId": 2,
   "PlayerFantasyTeam": 7,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 12,
   "PlayerRosterSlot": "RB"
 },
 {
   "Week": 1,
   "PlayerName": "Brandon Aiyuk",
   "PlayerScoreActual": "24.9",
   "PlayerScoreProjected": "6.4750606362",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 7,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 25,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Tyler Lockett",
   "PlayerScoreActual": "1.0",
   "PlayerScoreProjected": "8.101178719",
   "PlayerRosterSlotId": 23,
   "PlayerFantasyTeam": 7,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 26,
   "PlayerRosterSlot": "FLEX"
 },
 {
   "Week": 1,
   "PlayerName": "AJ Dillon",
   "PlayerScoreActual": "3.6000000000000005",
   "PlayerScoreProjected": "9.274262851",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 7,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "QUESTIONABLE",
   "ProTeam": 9,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Ezekiel Elliott",
   "PlayerScoreActual": "2.3000000000000007",
   "PlayerScoreProjected": "6.349929219800002",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 7,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 17,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Pat Freiermuth",
   "PlayerScoreActual": "6.3",
   "PlayerScoreProjected": "5.4943892110000006",
   "PlayerRosterSlotId": 6,
   "PlayerFantasyTeam": 7,
   "Position": "TE",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 23,
   "PlayerRosterSlot": "TE"
 },
 {
   "Week": 1,
   "PlayerName": "Kirk Cousins",
   "PlayerScoreActual": "16.46",
   "PlayerScoreProjected": "17.3527857947",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 7,
   "Position": "QB",
   "Injured": true,
   "InjuryStatus": "INJURY_RESERVE",
   "ProTeam": 16,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Jakobi Meyers",
   "PlayerScoreActual": "20.1",
   "PlayerScoreProjected": "6.513233851520001",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 7,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 13,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Harrison Butker",
   "PlayerScoreActual": "8.0",
   "PlayerScoreProjected": "8.653946091999998",
   "PlayerRosterSlotId": 17,
   "PlayerFantasyTeam": 7,
   "Position": "K",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 12,
   "PlayerRosterSlot": "K"
 },
 {
   "Week": 1,
   "PlayerName": "Ravens D/ST",
   "PlayerScoreActual": "10.0",
   "PlayerScoreProjected": "8.209413433000002",
   "PlayerRosterSlotId": 16,
   "PlayerFantasyTeam": 7,
   "Position": "D/ST",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 33,
   "PlayerRosterSlot": "D/ST"
 },
 {
   "Week": 1,
   "PlayerName": "Deon Jackson",
   "PlayerScoreActual": "-1.1999999999999995",
   "PlayerScoreProjected": "8.707161248",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 7,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 19,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Marvin Mims Jr.",
   "PlayerScoreActual": "0.9",
   "PlayerScoreProjected": "5.694721768",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 7,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 7,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Tyreek Hill",
   "PlayerScoreActual": "33.5",
   "PlayerScoreProjected": "13.278642176",
   "PlayerRosterSlotId": 4,
   "PlayerFantasyTeam": 10,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 15,
   "PlayerRosterSlot": "WR"
 },
 {
   "Week": 1,
   "PlayerName": "Travis Etienne Jr.",
   "PlayerScoreActual": "16.4",
   "PlayerScoreProjected": "12.525654475999998",
   "PlayerRosterSlotId": 2,
   "PlayerFantasyTeam": 10,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 30,
   "PlayerRosterSlot": "RB"
 },
 {
   "Week": 1,
   "PlayerName": "Mark Andrews",
   "PlayerScoreActual": "0.0",
   "PlayerScoreProjected": "0.0",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 10,
   "Position": "TE",
   "Injured": true,
   "InjuryStatus": "INJURY_RESERVE",
   "ProTeam": 33,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Joe Burrow",
   "PlayerScoreActual": "3.18",
   "PlayerScoreProjected": "19.761967064",
   "PlayerRosterSlotId": 0,
   "PlayerFantasyTeam": 10,
   "Position": "QB",
   "Injured": true,
   "InjuryStatus": "INJURY_RESERVE",
   "ProTeam": 4,
   "PlayerRosterSlot": "QB"
 },
 {
   "Week": 1,
   "PlayerName": "Javonte Williams",
   "PlayerScoreActual": "5.7",
   "PlayerScoreProjected": "9.047066312000002",
   "PlayerRosterSlotId": 2,
   "PlayerFantasyTeam": 10,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 7,
   "PlayerRosterSlot": "RB"
 },
 {
   "Week": 1,
   "PlayerName": "DeAndre Hopkins",
   "PlayerScoreActual": "6.5",
   "PlayerScoreProjected": "7.723195709000001",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 10,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 10,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Marquise Brown",
   "PlayerScoreActual": "5.700000000000001",
   "PlayerScoreProjected": "7.647520452000001",
   "PlayerRosterSlotId": 4,
   "PlayerFantasyTeam": 10,
   "Position": "WR",
   "Injured": true,
   "InjuryStatus": "INJURY_RESERVE",
   "ProTeam": 22,
   "PlayerRosterSlot": "WR"
 },
 {
   "Week": 1,
   "PlayerName": "Samaje Perine",
   "PlayerScoreActual": "7.800000000000001",
   "PlayerScoreProjected": "9.653995080000001",
   "PlayerRosterSlotId": 23,
   "PlayerFantasyTeam": 10,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 7,
   "PlayerRosterSlot": "FLEX"
 },
 {
   "Week": 1,
   "PlayerName": "Devin Singletary",
   "PlayerScoreActual": "1.5",
   "PlayerScoreProjected": "5.623430647",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 10,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 34,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Quentin Johnston",
   "PlayerScoreActual": "0.9",
   "PlayerScoreProjected": "3.9627539810000005",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 10,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 24,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "DJ Chark Jr.",
   "PlayerScoreActual": "0.0",
   "PlayerScoreProjected": "0.0",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 10,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 29,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Rondale Moore",
   "PlayerScoreActual": "4.5",
   "PlayerScoreProjected": "5.0396123054",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 10,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 22,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Chigoziem Okonkwo",
   "PlayerScoreActual": "0.0",
   "PlayerScoreProjected": "4.9599231679",
   "PlayerRosterSlotId": 6,
   "PlayerFantasyTeam": 10,
   "Position": "TE",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 10,
   "PlayerRosterSlot": "TE"
 },
 {
   "Week": 1,
   "PlayerName": "K.J. Osborn",
   "PlayerScoreActual": "3.1",
   "PlayerScoreProjected": "4.976622110999999",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 10,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 16,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Bengals D/ST",
   "PlayerScoreActual": "7.0",
   "PlayerScoreProjected": "6.488258251",
   "PlayerRosterSlotId": 16,
   "PlayerFantasyTeam": 10,
   "Position": "D/ST",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 4,
   "PlayerRosterSlot": "D/ST"
 },
 {
   "Week": 1,
   "PlayerName": "Tyler Bass",
   "PlayerScoreActual": "13.0",
   "PlayerScoreProjected": "8.268849826",
   "PlayerRosterSlotId": 17,
   "PlayerFantasyTeam": 10,
   "Position": "K",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 2,
   "PlayerRosterSlot": "K"
 },
 {
   "Week": 1,
   "PlayerName": "Ja'Marr Chase",
   "PlayerScoreActual": "4.1000000000000005",
   "PlayerScoreProjected": "13.5151778225",
   "PlayerRosterSlotId": 4,
   "PlayerFantasyTeam": 11,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 4,
   "PlayerRosterSlot": "WR"
 },
 {
   "Week": 1,
   "PlayerName": "Tee Higgins",
   "PlayerScoreActual": "0.0",
   "PlayerScoreProjected": "9.179537573",
   "PlayerRosterSlotId": 4,
   "PlayerFantasyTeam": 11,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "QUESTIONABLE",
   "ProTeam": 4,
   "PlayerRosterSlot": "WR"
 },
 {
   "Week": 1,
   "PlayerName": "Jahmyr Gibbs",
   "PlayerScoreActual": "6.0",
   "PlayerScoreProjected": "10.484886790000003",
   "PlayerRosterSlotId": 2,
   "PlayerFantasyTeam": 11,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 8,
   "PlayerRosterSlot": "RB"
 },
 {
   "Week": 1,
   "PlayerName": "Keenan Allen",
   "PlayerScoreActual": "8.200000000000001",
   "PlayerScoreProjected": "8.037879303",
   "PlayerRosterSlotId": 23,
   "PlayerFantasyTeam": 11,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "QUESTIONABLE",
   "ProTeam": 24,
   "PlayerRosterSlot": "FLEX"
 },
 {
   "Week": 1,
   "PlayerName": "Cam Akers",
   "PlayerScoreActual": "8.9",
   "PlayerScoreProjected": "11.248336209999998",
   "PlayerRosterSlotId": 2,
   "PlayerFantasyTeam": 11,
   "Position": "RB",
   "Injured": true,
   "InjuryStatus": "INJURY_RESERVE",
   "ProTeam": 16,
   "PlayerRosterSlot": "RB"
 },
 {
   "Week": 1,
   "PlayerName": "Drake London",
   "PlayerScoreActual": "0.0",
   "PlayerScoreProjected": "7.616334019",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 11,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 1,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Kyle Pitts",
   "PlayerScoreActual": "4.4",
   "PlayerScoreProjected": "6.620796533000001",
   "PlayerRosterSlotId": 6,
   "PlayerFantasyTeam": 11,
   "Position": "TE",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 1,
   "PlayerRosterSlot": "TE"
 },
 {
   "Week": 1,
   "PlayerName": "Zay Flowers",
   "PlayerScoreActual": "8.700000000000001",
   "PlayerScoreProjected": "6.7930632985",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 11,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 33,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Dak Prescott",
   "PlayerScoreActual": "6.32",
   "PlayerScoreProjected": "18.343170991",
   "PlayerRosterSlotId": 0,
   "PlayerFantasyTeam": 11,
   "Position": "QB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 6,
   "PlayerRosterSlot": "QB"
 },
 {
   "Week": 1,
   "PlayerName": "Allen Lazard",
   "PlayerScoreActual": "4.6000000000000005",
   "PlayerScoreProjected": "6.082472997200001",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 11,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 20,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Tank Bigsby",
   "PlayerScoreActual": "5.3",
   "PlayerScoreProjected": "4.900897969900001",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 11,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 30,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Hunter Renfrow",
   "PlayerScoreActual": "0.0",
   "PlayerScoreProjected": "4.747590784000001",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 11,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 13,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "D'Onta Foreman",
   "PlayerScoreActual": "2.4000000000000004",
   "PlayerScoreProjected": "4.8127381208",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 11,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 3,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Younghoe Koo",
   "PlayerScoreActual": "7.0",
   "PlayerScoreProjected": "8.116905085",
   "PlayerRosterSlotId": 17,
   "PlayerFantasyTeam": 11,
   "Position": "K",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 1,
   "PlayerRosterSlot": "K"
 },
 {
   "Week": 1,
   "PlayerName": "Bills D/ST",
   "PlayerScoreActual": "5.0",
   "PlayerScoreProjected": "6.053294685",
   "PlayerRosterSlotId": 16,
   "PlayerFantasyTeam": 11,
   "Position": "D/ST",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 2,
   "PlayerRosterSlot": "D/ST"
 },
 {
   "Week": 1,
   "PlayerName": "Cole Kmet",
   "PlayerScoreActual": "4.4",
   "PlayerScoreProjected": "5.0308202920000005",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 11,
   "Position": "TE",
   "Injured": false,
   "InjuryStatus": "QUESTIONABLE",
   "ProTeam": 3,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Nick Chubb",
   "PlayerScoreActual": "12.700000000000001",
   "PlayerScoreProjected": "13.481670164000002",
   "PlayerRosterSlotId": 2,
   "PlayerFantasyTeam": 12,
   "Position": "RB",
   "Injured": true,
   "InjuryStatus": "INJURY_RESERVE",
   "ProTeam": 5,
   "PlayerRosterSlot": "RB"
 },
 {
   "Week": 1,
   "PlayerName": "Jaylen Waddle",
   "PlayerScoreActual": "7.800000000000001",
   "PlayerScoreProjected": "9.8400835716",
   "PlayerRosterSlotId": 4,
   "PlayerFantasyTeam": 12,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 15,
   "PlayerRosterSlot": "WR"
 },
 {
   "Week": 1,
   "PlayerName": "Patrick Mahomes",
   "PlayerScoreActual": "19.54",
   "PlayerScoreProjected": "24.667079786",
   "PlayerRosterSlotId": 0,
   "PlayerFantasyTeam": 12,
   "Position": "QB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 12,
   "PlayerRosterSlot": "QB"
 },
 {
   "Week": 1,
   "PlayerName": "Miles Sanders",
   "PlayerScoreActual": "7.800000000000001",
   "PlayerScoreProjected": "11.902624873999999",
   "PlayerRosterSlotId": 2,
   "PlayerFantasyTeam": 12,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 29,
   "PlayerRosterSlot": "RB"
 },
 {
   "Week": 1,
   "PlayerName": "DJ Moore",
   "PlayerScoreActual": "2.5",
   "PlayerScoreProjected": "8.628625360100001",
   "PlayerRosterSlotId": 4,
   "PlayerFantasyTeam": 12,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 3,
   "PlayerRosterSlot": "WR"
 },
 {
   "Week": 1,
   "PlayerName": "George Kittle",
   "PlayerScoreActual": "1.9000000000000001",
   "PlayerScoreProjected": "6.3221327336",
   "PlayerRosterSlotId": 6,
   "PlayerFantasyTeam": 12,
   "Position": "TE",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 25,
   "PlayerRosterSlot": "TE"
 },
 {
   "Week": 1,
   "PlayerName": "Jerry Jeudy",
   "PlayerScoreActual": "0.0",
   "PlayerScoreProjected": "0.0",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 12,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 7,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Jaxon Smith-Njigba",
   "PlayerScoreActual": "1.3",
   "PlayerScoreProjected": "6.149599398",
   "PlayerRosterSlotId": 23,
   "PlayerFantasyTeam": 12,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 26,
   "PlayerRosterSlot": "FLEX"
 },
 {
   "Week": 1,
   "PlayerName": "Rashaad Penny",
   "PlayerScoreActual": "0.0",
   "PlayerScoreProjected": "0.0",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 12,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 21,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Adam Thielen",
   "PlayerScoreActual": "1.2000000000000002",
   "PlayerScoreProjected": "5.817084562000001",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 12,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 29,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Jaylen Warren",
   "PlayerScoreActual": "1.8000000000000003",
   "PlayerScoreProjected": "5.096384181000001",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 12,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 23,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Tyler Boyd",
   "PlayerScoreActual": "1.0",
   "PlayerScoreProjected": "4.743371952",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 12,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 4,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Zay Jones",
   "PlayerScoreActual": "11.5",
   "PlayerScoreProjected": "5.510251535",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 12,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 30,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Anthony Richardson",
   "PlayerScoreActual": "20.92",
   "PlayerScoreProjected": "17.166275450999997",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 12,
   "Position": "QB",
   "Injured": true,
   "InjuryStatus": "INJURY_RESERVE",
   "ProTeam": 11,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Daniel Carlson",
   "PlayerScoreActual": "5.0",
   "PlayerScoreProjected": "8.3555135",
   "PlayerRosterSlotId": 17,
   "PlayerFantasyTeam": 12,
   "Position": "K",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 13,
   "PlayerRosterSlot": "K"
 },
 {
   "Week": 1,
   "PlayerName": "Dolphins D/ST",
   "PlayerScoreActual": "2.0",
   "PlayerScoreProjected": "6.443633677000001",
   "PlayerRosterSlotId": 16,
   "PlayerFantasyTeam": 12,
   "Position": "D/ST",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 15,
   "PlayerRosterSlot": "D/ST"
 },
 {
   "Week": 1,
   "PlayerName": "Bijan Robinson",
   "PlayerScoreActual": "14.3",
   "PlayerScoreProjected": "14.289519086",
   "PlayerRosterSlotId": 2,
   "PlayerFantasyTeam": 13,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 1,
   "PlayerRosterSlot": "RB"
 },
 {
   "Week": 1,
   "PlayerName": "Garrett Wilson",
   "PlayerScoreActual": "9.4",
   "PlayerScoreProjected": "10.816058143000001",
   "PlayerRosterSlotId": 4,
   "PlayerFantasyTeam": 13,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 20,
   "PlayerRosterSlot": "WR"
 },
 {
   "Week": 1,
   "PlayerName": "Dameon Pierce",
   "PlayerScoreActual": "4.7",
   "PlayerScoreProjected": "11.123865647",
   "PlayerRosterSlotId": 2,
   "PlayerFantasyTeam": 13,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 34,
   "PlayerRosterSlot": "RB"
 },
 {
   "Week": 1,
   "PlayerName": "Rhamondre Stevenson",
   "PlayerScoreActual": "8.9",
   "PlayerScoreProjected": "11.416342629",
   "PlayerRosterSlotId": 23,
   "PlayerFantasyTeam": 13,
   "Position": "RB",
   "Injured": true,
   "InjuryStatus": "INJURY_RESERVE",
   "ProTeam": 17,
   "PlayerRosterSlot": "FLEX"
 },
 {
   "Week": 1,
   "PlayerName": "Mike Evans",
   "PlayerScoreActual": "12.600000000000001",
   "PlayerScoreProjected": "9.096813589",
   "PlayerRosterSlotId": 4,
   "PlayerFantasyTeam": 13,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 27,
   "PlayerRosterSlot": "WR"
 },
 {
   "Week": 1,
   "PlayerName": "Darren Waller",
   "PlayerScoreActual": "3.6",
   "PlayerScoreProjected": "7.542638384000001",
   "PlayerRosterSlotId": 6,
   "PlayerFantasyTeam": 13,
   "Position": "TE",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 19,
   "PlayerRosterSlot": "TE"
 },
 {
   "Week": 1,
   "PlayerName": "Diontae Johnson",
   "PlayerScoreActual": "4.800000000000001",
   "PlayerScoreProjected": "7.8422734947",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 13,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 23,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Antonio Gibson",
   "PlayerScoreActual": "-0.10000000000000009",
   "PlayerScoreProjected": "7.710872507000001",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 13,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 28,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Deshaun Watson",
   "PlayerScoreActual": "20.66",
   "PlayerScoreProjected": "18.445531418999998",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 13,
   "Position": "QB",
   "Injured": true,
   "InjuryStatus": "INJURY_RESERVE",
   "ProTeam": 5,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Evan Hull",
   "PlayerScoreActual": "0.7000000000000001",
   "PlayerScoreProjected": "7.310781477000001",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 13,
   "Position": "RB",
   "Injured": true,
   "InjuryStatus": "INJURY_RESERVE",
   "ProTeam": 11,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Jonathan Mingo",
   "PlayerScoreActual": "1.7000000000000002",
   "PlayerScoreProjected": "5.886763612000001",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 13,
   "Position": "WR",
   "Injured": true,
   "InjuryStatus": "INJURY_RESERVE",
   "ProTeam": 29,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Tua Tagovailoa",
   "PlayerScoreActual": "27.14",
   "PlayerScoreProjected": "17.599452270599997",
   "PlayerRosterSlotId": 0,
   "PlayerFantasyTeam": 13,
   "Position": "QB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 15,
   "PlayerRosterSlot": "QB"
 },
 {
   "Week": 1,
   "PlayerName": "Van Jefferson",
   "PlayerScoreActual": "2.4000000000000004",
   "PlayerScoreProjected": "7.164518816000001",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 13,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 1,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Cowboys D/ST",
   "PlayerScoreActual": "32.0",
   "PlayerScoreProjected": "7.216809232",
   "PlayerRosterSlotId": 16,
   "PlayerFantasyTeam": 13,
   "Position": "D/ST",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 6,
   "PlayerRosterSlot": "D/ST"
 },
 {
   "Week": 1,
   "PlayerName": "Jake Elliott",
   "PlayerScoreActual": "18.0",
   "PlayerScoreProjected": "8.551449827999999",
   "PlayerRosterSlotId": 17,
   "PlayerFantasyTeam": 13,
   "Position": "K",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 21,
   "PlayerRosterSlot": "K"
 },
 {
   "Week": 1,
   "PlayerName": "Jake Ferguson",
   "PlayerScoreActual": "1.1",
   "PlayerScoreProjected": "4.072298524",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 13,
   "Position": "TE",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 6,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Derrick Henry",
   "PlayerScoreActual": "11.900000000000002",
   "PlayerScoreProjected": "14.720433575000003",
   "PlayerRosterSlotId": 2,
   "PlayerFantasyTeam": 14,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 10,
   "PlayerRosterSlot": "RB"
 },
 {
   "Week": 1,
   "PlayerName": "CeeDee Lamb",
   "PlayerScoreActual": "7.7",
   "PlayerScoreProjected": "11.3964643034",
   "PlayerRosterSlotId": 4,
   "PlayerFantasyTeam": 14,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 6,
   "PlayerRosterSlot": "WR"
 },
 {
   "Week": 1,
   "PlayerName": "Aaron Jones",
   "PlayerScoreActual": "24.700000000000003",
   "PlayerScoreProjected": "12.006352610999999",
   "PlayerRosterSlotId": 2,
   "PlayerFantasyTeam": 14,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "QUESTIONABLE",
   "ProTeam": 9,
   "PlayerRosterSlot": "RB"
 },
 {
   "Week": 1,
   "PlayerName": "Christian Watson",
   "PlayerScoreActual": "0.0",
   "PlayerScoreProjected": "0.0",
   "PlayerRosterSlotId": 4,
   "PlayerFantasyTeam": 14,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "QUESTIONABLE",
   "ProTeam": 9,
   "PlayerRosterSlot": "WR"
 },
 {
   "Week": 1,
   "PlayerName": "Jonathan Taylor",
   "PlayerScoreActual": "0.0",
   "PlayerScoreProjected": "0.0",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 14,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 11,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Chris Godwin",
   "PlayerScoreActual": "5.1000000000000005",
   "PlayerScoreProjected": "8.264932734299999",
   "PlayerRosterSlotId": 23,
   "PlayerFantasyTeam": 14,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "QUESTIONABLE",
   "ProTeam": 27,
   "PlayerRosterSlot": "FLEX"
 },
 {
   "Week": 1,
   "PlayerName": "Trevor Lawrence",
   "PlayerScoreActual": "17.740000000000002",
   "PlayerScoreProjected": "18.452728558",
   "PlayerRosterSlotId": 0,
   "PlayerFantasyTeam": 14,
   "Position": "QB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 30,
   "PlayerRosterSlot": "QB"
 },
 {
   "Week": 1,
   "PlayerName": "Michael Thomas",
   "PlayerScoreActual": "6.1000000000000005",
   "PlayerScoreProjected": "6.931969251",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 14,
   "Position": "WR",
   "Injured": true,
   "InjuryStatus": "INJURY_RESERVE",
   "ProTeam": 18,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Elijah Mitchell",
   "PlayerScoreActual": "1.0",
   "PlayerScoreProjected": "5.2665425542",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 14,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 25,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Justin Tucker",
   "PlayerScoreActual": "5.0",
   "PlayerScoreProjected": "8.986251057",
   "PlayerRosterSlotId": 17,
   "PlayerFantasyTeam": 14,
   "Position": "K",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 33,
   "PlayerRosterSlot": "K"
 },
 {
   "Week": 1,
   "PlayerName": "David Njoku",
   "PlayerScoreActual": "2.4000000000000004",
   "PlayerScoreProjected": "6.2300795849",
   "PlayerRosterSlotId": 6,
   "PlayerFantasyTeam": 14,
   "Position": "TE",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 5,
   "PlayerRosterSlot": "TE"
 },
 {
   "Week": 1,
   "PlayerName": "Tyjae Spears",
   "PlayerScoreActual": "2.8000000000000003",
   "PlayerScoreProjected": "2.2681457544000003",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 14,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 10,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Darnell Mooney",
   "PlayerScoreActual": "11.3",
   "PlayerScoreProjected": "5.8640158519000005",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 14,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "QUESTIONABLE",
   "ProTeam": 3,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "49ers D/ST",
   "PlayerScoreActual": "12.0",
   "PlayerScoreProjected": "7.472978758",
   "PlayerRosterSlotId": 16,
   "PlayerFantasyTeam": 14,
   "Position": "D/ST",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 25,
   "PlayerRosterSlot": "D/ST"
 },
 {
   "Week": 1,
   "PlayerName": "Zach Ertz",
   "PlayerScoreActual": "2.1",
   "PlayerScoreProjected": "3.652216858",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 14,
   "Position": "TE",
   "Injured": false,
   "InjuryStatus": "QUESTIONABLE",
   "ProTeam": 0,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Kyler Murray",
   "PlayerScoreActual": "0.0",
   "PlayerScoreProjected": "0.0",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 14,
   "Position": "QB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 22,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Justin Jefferson",
   "PlayerScoreActual": "15.0",
   "PlayerScoreProjected": "12.932456843800002",
   "PlayerRosterSlotId": 4,
   "PlayerFantasyTeam": 15,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 16,
   "PlayerRosterSlot": "WR"
 },
 {
   "Week": 1,
   "PlayerName": "Joe Mixon",
   "PlayerScoreActual": "7.300000000000001",
   "PlayerScoreProjected": "11.25993214",
   "PlayerRosterSlotId": 2,
   "PlayerFantasyTeam": 15,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 4,
   "PlayerRosterSlot": "RB"
 },
 {
   "Week": 1,
   "PlayerName": "DK Metcalf",
   "PlayerScoreActual": "10.7",
   "PlayerScoreProjected": "10.688305457000002",
   "PlayerRosterSlotId": 4,
   "PlayerFantasyTeam": 15,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 26,
   "PlayerRosterSlot": "WR"
 },
 {
   "Week": 1,
   "PlayerName": "Breece Hall",
   "PlayerScoreActual": "14.700000000000001",
   "PlayerScoreProjected": "5.782751047",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 15,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 20,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Justin Herbert",
   "PlayerScoreActual": "20.86",
   "PlayerScoreProjected": "16.887623412",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 15,
   "Position": "QB",
   "Injured": true,
   "InjuryStatus": "INJURY_RESERVE",
   "ProTeam": 24,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "D'Andre Swift",
   "PlayerScoreActual": "0.30000000000000004",
   "PlayerScoreProjected": "9.163626848999998",
   "PlayerRosterSlotId": 2,
   "PlayerFantasyTeam": 15,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 21,
   "PlayerRosterSlot": "RB"
 },
 {
   "Week": 1,
   "PlayerName": "Dallas Goedert",
   "PlayerScoreActual": "0.0",
   "PlayerScoreProjected": "5.636066755",
   "PlayerRosterSlotId": 6,
   "PlayerFantasyTeam": 15,
   "Position": "TE",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 21,
   "PlayerRosterSlot": "TE"
 },
 {
   "Week": 1,
   "PlayerName": "Brandin Cooks",
   "PlayerScoreActual": "2.2",
   "PlayerScoreProjected": "7.7925926923",
   "PlayerRosterSlotId": 23,
   "PlayerFantasyTeam": 15,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 6,
   "PlayerRosterSlot": "FLEX"
 },
 {
   "Week": 1,
   "PlayerName": "Tyler Allgeier",
   "PlayerScoreActual": "21.4",
   "PlayerScoreProjected": "7.505005666300001",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 15,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 1,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Kareem Hunt",
   "PlayerScoreActual": "21.4",
   "PlayerScoreProjected": "0.0",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 15,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 5,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Geno Smith",
   "PlayerScoreActual": "9.08",
   "PlayerScoreProjected": "19.218552337",
   "PlayerRosterSlotId": 0,
   "PlayerFantasyTeam": 15,
   "Position": "QB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 26,
   "PlayerRosterSlot": "QB"
 },
 {
   "Week": 1,
   "PlayerName": "Dalton Kincaid",
   "PlayerScoreActual": "2.6",
   "PlayerScoreProjected": "4.035752246",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 15,
   "Position": "TE",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 2,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Steelers D/ST",
   "PlayerScoreActual": "4.0",
   "PlayerScoreProjected": "7.085425373000001",
   "PlayerRosterSlotId": 16,
   "PlayerFantasyTeam": 15,
   "Position": "D/ST",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 23,
   "PlayerRosterSlot": "D/ST"
 },
 {
   "Week": 1,
   "PlayerName": "Marquez Valdes-Scantling",
   "PlayerScoreActual": "4.800000000000001",
   "PlayerScoreProjected": "7.030673405000001",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 15,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 12,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Isaiah Hodgins",
   "PlayerScoreActual": "0.40000000000000036",
   "PlayerScoreProjected": "4.113959041000001",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 15,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 19,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Cairo Santos",
   "PlayerScoreActual": "7.0",
   "PlayerScoreProjected": "8.318052078000001",
   "PlayerRosterSlotId": 17,
   "PlayerFantasyTeam": 15,
   "Position": "K",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 3,
   "PlayerRosterSlot": "K"
 },
 {
   "Week": 1,
   "PlayerName": "Austin Ekeler",
   "PlayerScoreActual": "22.400000000000002",
   "PlayerScoreProjected": "13.010204801000002",
   "PlayerRosterSlotId": 2,
   "PlayerFantasyTeam": 16,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 24,
   "PlayerRosterSlot": "RB"
 },
 {
   "Week": 1,
   "PlayerName": "Deebo Samuel",
   "PlayerScoreActual": "6.3",
   "PlayerScoreProjected": "9.784285347",
   "PlayerRosterSlotId": 4,
   "PlayerFantasyTeam": 16,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 25,
   "PlayerRosterSlot": "WR"
 },
 {
   "Week": 1,
   "PlayerName": "Najee Harris",
   "PlayerScoreActual": "3.3000000000000003",
   "PlayerScoreProjected": "10.495830696",
   "PlayerRosterSlotId": 2,
   "PlayerFantasyTeam": 16,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 23,
   "PlayerRosterSlot": "RB"
 },
 {
   "Week": 1,
   "PlayerName": "Rachaad White",
   "PlayerScoreActual": "4.9",
   "PlayerScoreProjected": "11.059691138",
   "PlayerRosterSlotId": 23,
   "PlayerFantasyTeam": 16,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 27,
   "PlayerRosterSlot": "FLEX"
 },
 {
   "Week": 1,
   "PlayerName": "James Conner",
   "PlayerScoreActual": "7.0",
   "PlayerScoreProjected": "11.735524197",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 16,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 22,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "T.J. Hockenson",
   "PlayerScoreActual": "3.5",
   "PlayerScoreProjected": "7.682696624000001",
   "PlayerRosterSlotId": 6,
   "PlayerFantasyTeam": 16,
   "Position": "TE",
   "Injured": true,
   "InjuryStatus": "INJURY_RESERVE",
   "ProTeam": 16,
   "PlayerRosterSlot": "TE"
 },
 {
   "Week": 1,
   "PlayerName": "Dalvin Cook",
   "PlayerScoreActual": "5.9",
   "PlayerScoreProjected": "9.374402887",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 16,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 33,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Skyy Moore",
   "PlayerScoreActual": "0.4",
   "PlayerScoreProjected": "7.980200483700001",
   "PlayerRosterSlotId": 4,
   "PlayerFantasyTeam": 16,
   "Position": "WR",
   "Injured": true,
   "InjuryStatus": "INJURY_RESERVE",
   "ProTeam": 12,
   "PlayerRosterSlot": "WR"
 },
 {
   "Week": 1,
   "PlayerName": "Courtland Sutton",
   "PlayerScoreActual": "9.2",
   "PlayerScoreProjected": "9.005443848999999",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 16,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "QUESTIONABLE",
   "ProTeam": 7,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "JuJu Smith-Schuster",
   "PlayerScoreActual": "3.3000000000000003",
   "PlayerScoreProjected": "6.119515532",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 16,
   "Position": "WR",
   "Injured": true,
   "InjuryStatus": "INJURY_RESERVE",
   "ProTeam": 17,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Nico Collins",
   "PlayerScoreActual": "8.0",
   "PlayerScoreProjected": "6.484749171",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 16,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 34,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Parris Campbell",
   "PlayerScoreActual": "0.2",
   "PlayerScoreProjected": "4.1369712088999995",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 16,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 19,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Ty Chandler",
   "PlayerScoreActual": "1.8",
   "PlayerScoreProjected": "5.468815698200001",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 16,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 16,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Saints D/ST",
   "PlayerScoreActual": "10.0",
   "PlayerScoreProjected": "6.9964204080000005",
   "PlayerRosterSlotId": 16,
   "PlayerFantasyTeam": 16,
   "Position": "D/ST",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 18,
   "PlayerRosterSlot": "D/ST"
 },
 {
   "Week": 1,
   "PlayerName": "Greg Zuerlein",
   "PlayerScoreActual": "11.0",
   "PlayerScoreProjected": "7.989352642000001",
   "PlayerRosterSlotId": 17,
   "PlayerFantasyTeam": 16,
   "Position": "K",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 20,
   "PlayerRosterSlot": "K"
 },
 {
   "Week": 1,
   "PlayerName": "Russell Wilson",
   "PlayerScoreActual": "15.18",
   "PlayerScoreProjected": "18.625858866",
   "PlayerRosterSlotId": 0,
   "PlayerFantasyTeam": 16,
   "Position": "QB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 7,
   "PlayerRosterSlot": "QB"
 },
 {
   "Week": 1,
   "PlayerName": "Tony Pollard",
   "PlayerScoreActual": "20.2",
   "PlayerScoreProjected": "14.731143474000001",
   "PlayerRosterSlotId": 2,
   "PlayerFantasyTeam": 17,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 6,
   "PlayerRosterSlot": "RB"
 },
 {
   "Week": 1,
   "PlayerName": "Cooper Kupp",
   "PlayerScoreActual": "0.0",
   "PlayerScoreProjected": "0.0",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 17,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 14,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Kenneth Walker III",
   "PlayerScoreActual": "6.7",
   "PlayerScoreProjected": "12.815878255000001",
   "PlayerRosterSlotId": 2,
   "PlayerFantasyTeam": 17,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 26,
   "PlayerRosterSlot": "RB"
 },
 {
   "Week": 1,
   "PlayerName": "Calvin Ridley",
   "PlayerScoreActual": "16.1",
   "PlayerScoreProjected": "9.2186488596",
   "PlayerRosterSlotId": 4,
   "PlayerFantasyTeam": 17,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 30,
   "PlayerRosterSlot": "WR"
 },
 {
   "Week": 1,
   "PlayerName": "Alvin Kamara",
   "PlayerScoreActual": "0.0",
   "PlayerScoreProjected": "0.0",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 17,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "QUESTIONABLE",
   "ProTeam": 18,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Mike Williams",
   "PlayerScoreActual": "4.5",
   "PlayerScoreProjected": "8.206418548000002",
   "PlayerRosterSlotId": 4,
   "PlayerFantasyTeam": 17,
   "Position": "WR",
   "Injured": true,
   "InjuryStatus": "INJURY_RESERVE",
   "ProTeam": 24,
   "PlayerRosterSlot": "WR"
 },
 {
   "Week": 1,
   "PlayerName": "George Pickens",
   "PlayerScoreActual": "3.6",
   "PlayerScoreProjected": "6.661803577300001",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 17,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 23,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Raheem Mostert",
   "PlayerScoreActual": "11.0",
   "PlayerScoreProjected": "10.436821445000001",
   "PlayerRosterSlotId": 23,
   "PlayerFantasyTeam": 17,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 15,
   "PlayerRosterSlot": "FLEX"
 },
 {
   "Week": 1,
   "PlayerName": "Odell Beckham Jr.",
   "PlayerScoreActual": "3.7",
   "PlayerScoreProjected": "7.232539775599999",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 17,
   "Position": "WR",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 33,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Damien Harris",
   "PlayerScoreActual": "1.9000000000000001",
   "PlayerScoreProjected": "4.189293261",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 17,
   "Position": "RB",
   "Injured": true,
   "InjuryStatus": "INJURY_RESERVE",
   "ProTeam": 2,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Gus Edwards",
   "PlayerScoreActual": "5.2",
   "PlayerScoreProjected": "5.2372184888",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 17,
   "Position": "RB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 33,
   "PlayerRosterSlot": "Bench"
 },
 {
   "Week": 1,
   "PlayerName": "Dalton Schultz",
   "PlayerScoreActual": "0.4",
   "PlayerScoreProjected": "4.7921899969999995",
   "PlayerRosterSlotId": 6,
   "PlayerFantasyTeam": 17,
   "Position": "TE",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 34,
   "PlayerRosterSlot": "TE"
 },
 {
   "Week": 1,
   "PlayerName": "Jared Goff",
   "PlayerScoreActual": "14.020000000000001",
   "PlayerScoreProjected": "15.748741264",
   "PlayerRosterSlotId": 0,
   "PlayerFantasyTeam": 17,
   "Position": "QB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 8,
   "PlayerRosterSlot": "QB"
 },
 {
   "Week": 1,
   "PlayerName": "Jets D/ST",
   "PlayerScoreActual": "20.0",
   "PlayerScoreProjected": "6.286923268",
   "PlayerRosterSlotId": 16,
   "PlayerFantasyTeam": 17,
   "Position": "D/ST",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 20,
   "PlayerRosterSlot": "D/ST"
 },
 {
   "Week": 1,
   "PlayerName": "Graham Gano",
   "PlayerScoreActual": "0.0",
   "PlayerScoreProjected": "8.271997674",
   "PlayerRosterSlotId": 17,
   "PlayerFantasyTeam": 17,
   "Position": "K",
   "Injured": true,
   "InjuryStatus": "INJURY_RESERVE",
   "ProTeam": 19,
   "PlayerRosterSlot": "K"
 },
 {
   "Week": 1,
   "PlayerName": "C.J. Stroud",
   "PlayerScoreActual": "9.68",
   "PlayerScoreProjected": "12.9246789936",
   "PlayerRosterSlotId": 20,
   "PlayerFantasyTeam": 17,
   "Position": "QB",
   "Injured": false,
   "InjuryStatus": "ACTIVE",
   "ProTeam": 34,
   "PlayerRosterSlot": "Bench"
 }
]