export const sleeperSettings = {
    2025:{
  "name": "Uncle Brian FFL",
  "status": "in_season",
  "metadata": {
    "auto_continue": "on",
    "division_1": "North",
    "division_2": "Central",
    "division_3": "West",
    "keeper_deadline": "0"
  },
  "settings": {
    "best_ball": 0,
    "waiver_budget": 100,
    "disable_adds": 0,
    "divisions": 3,
    "capacity_override": 0,
    "taxi_deadline": 4,
    "draft_rounds": 4,
    "reserve_allow_na": 0,
    "start_week": 1,
    "playoff_seed_type": 0,
    "playoff_teams": 6,
    "veto_votes_needed": 6,
    "num_teams": 12,
    "daily_waivers_hour": 0,
    "playoff_type": 0,
    "taxi_slots": 3,
    "sub_start_time_eligibility": 1,
    "last_scored_leg": 1,
    "daily_waivers_days": 5461,
    "sub_lock_if_starter_active": 0,
    "playoff_week_start": 15,
    "waiver_clear_days": 1,
    "reserve_allow_doubtful": 0,
    "commissioner_direct_invite": 0,
    "veto_auto_poll": 0,
    "reserve_allow_dnr": 0,
    "taxi_allow_vets": 0,
    "waiver_day_of_week": 2,
    "playoff_round_type": 0,
    "reserve_allow_out": 0,
    "reserve_allow_sus": 0,
    "veto_show_votes": 0,
    "trade_deadline": 11,
    "taxi_years": 2,
    "daily_waivers": 0,
    "faab_suggestions": 1,
    "disable_trades": 0,
    "pick_trading": 1,
    "type": 2,
    "max_keepers": 1,
    "waiver_type": 2,
    "max_subs": 2,
    "league_average_match": 0,
    "trade_review_days": 0,
    "bench_lock": 1,
    "offseason_adds": 0,
    "leg": 1,
    "reserve_slots": 2,
    "reserve_allow_cov": 0,
    "daily_waivers_last_ran": 1
  },
  "avatar": null,
  "company_id": null,
  "last_message_id": "1270452437521539072",
  "shard": 829,
  "season": "2025",
  "season_type": "regular",
  "scoring_settings": {
    "sack": 1,
    "fgm_40_49": 4,
    "pass_int": -2,
    "pts_allow_0": 10,
    "pass_2pt": 2,
    "st_td": 0,
    "rec_td": 6,
    "fgm_30_39": 3,
    "fgm_50_59": 5,
    "xpmiss": -1,
    "rush_td": 6,
    "rec_2pt": 2,
    "st_fum_rec": 0,
    "fgmiss": 0,
    "ff": 0,
    "fgmiss_30_39": -1,
    "rec": 0,
    "pts_allow_14_20": 1,
    "fgm_0_19": 3,
    "int": 2,
    "def_st_fum_rec": 2,
    "fum_lost": -2,
    "pts_allow_1_6": 7,
    "fgm_60p": 0,
    "fgmiss_20_29": -1,
    "fgm_20_29": 3,
    "pts_allow_21_27": 0,
    "xpm": 1,
    "fgmiss_0_19": -1,
    "rush_2pt": 2,
    "fum_rec": 2,
    "def_st_td": 6,
    "def_td": 6,
    "safe": 4,
    "pass_yd": 0.04,
    "fgmiss_40_49": -1,
    "blk_kick": 2,
    "pass_td": 4,
    "rush_yd": 0.1,
    "fum": 0,
    "pts_allow_28_34": -1,
    "pts_allow_35p": -4,
    "fum_rec_td": 6,
    "rec_yd": 0.1,
    "def_st_ff": 0,
    "pts_allow_7_13": 4,
    "st_ff": 0
  },
  "sport": "nfl",
  "draft_id": "1263340154823639040",
  "last_author_avatar": null,
  "last_author_display_name": "sys",
  "last_author_id": "166666666666666666",
  "last_author_is_bot": true,
  "last_message_attachment": null,
  "last_message_text_map": null,
  "last_message_time": 1757261974271,
  "last_pinned_message_id": null,
  "last_read_id": null,
  "league_id": "1263340152806195200",
  "previous_league_id": null,
  "bracket_id": null,
  "bracket_overrides_id": null,
  "group_id": null,
  "loser_bracket_id": null,
  "loser_bracket_overrides_id": null,
  "roster_positions": [
    "QB",
    "RB",
    "RB",
    "WR",
    "WR",
    "TE",
    "FLEX",
    "FLEX",
    "K",
    "DEF",
    "BN",
    "BN",
    "BN",
    "BN",
    "BN",
    "BN",
    "BN",
    "BN",
    "BN",
    "BN",
    "BN",
    "BN"
  ],
  "total_rosters": 12
}
//,2026:
}